### ISSUE TITLE
Something is broken here

### ISSUE THREAD

**Issue by grvillic** [disuser/office-ui-fabric-react#105]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by annaowens** [comment]
Can I get more information?

**Comment by grvillic** [comment]
Like what sorry?

**Comment by grvillic** [comment]
Hello?!

**Comment by annaowens** [comment]
hi?

**Comment by grvillic** [comment]
Again

**Comment by grvillic** [comment]
Testing

**Comment by annaowens** [comment]
more info?

**Comment by annaowens** [comment]
more info?

**Comment by grvillic** [comment]
Are you sure about this?

**Comment by annaowens** [comment]
can you give more info?

**Comment by grvillic** [comment]
Testing

**Comment by annaowens** [comment]
one more time
